# Generated by Django 5.0.4 on 2024-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255, verbose_name="First name")),
                ("last_name", models.CharField(max_length=255, verbose_name="Last name")),
                ("phone", models.CharField(blank=True, max_length=255, verbose_name="Phone")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="Email")),
            ],
        ),
    ]
